# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

[collection_sources]

[sessions.ansible_test_integration_w_default_container]
include_devel = true
add_devel_like_branches = [
    ["felixfontein/ansible", "show-deprecations"],
]

[sessions.ansible_test_integration_w_default_container.core_python_versions]
"2.9" = ["3.5"]
"2.10" = ["3.5"]
"2.11" = ["2.6"]
"2.12" = ["3.5"]
"2.13" = ["3.6"]
"2.14" = ["3.9"]
"2.15" = ["3.5"]
"2.16" = ["3.7"]
"2.17" = ["3.8"]
"2.18" = ["3.9"]
"2.19" = ["3.9"]
