namespace: community
name: internal_test_tools
version: 0.1.1
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags:
  - collection testing
repository: https://github.com/ansible-collections/community.internal_test_tools
documentation: https://github.com/ansible-collection-migration/community.internal_test_tools/tree/master/docs
homepage: https://github.com/ansible-collections/community.internal_test_tools
issues: https://github.com/ansible-collections/community.internal_test_tools/issues
