---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

name: tools-tests
'on':
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
      - stable-*
  pull_request:
  # Run CI once per day (at 05:00 UTC)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test for each ansible-base version
  schedule:
    - cron: '0 5 * * *'

jobs:
  extra-sanity:
    name: Extra sanity tool
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/community/internal_test_tools

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ansible-core
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz coverage --disable-pip-version-check

      - name: Run sanity tests
        run: coverage run -p --source tools -m tools.run --color
        working-directory: ./ansible_collections/community/internal_test_tools

      - name: Combine coverage
        run: |
          coverage combine .coverage.*
          coverage report
          coverage xml -i
        working-directory: ./ansible_collections/community/internal_test_tools

      - name: Upload coverage stats
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
